### PR TITLE
use hammer.js

### PR DESCRIPTION
**Pull request by b051**

### CODE REVIEW

**Comment by davidgoli** [comment]
Please fix tests

**Comment by davidgoli** [comment]
@b051 please fix the tests

**Comment by b051** [comment]
@davidgoli hey, I did `app.import(app.bowerDirectory + '/hammerjs/hammer.js');` in ember-cli-build.js, and it clearly works, but by running `ember test`, it still reports 'Hammer is not defined'. any ideas?

**Comment by b051** [comment]
the error messages is gone if I add 'Hammer' into .jshintrc

**Pull request closed without merging**
