### PR TITLE
Update to ember-cli 2.16.2 (fix babel deprecation warnings)

### PR DESCRIPTION
**Pull request by veelci**
Also switched to ember-cli-code-coverage.

### CODE REVIEW

**Comment by veelci** [comment]
@davidgoli, any chance this could get merged in and published to npm?

**Review by davidgoli — APPROVED** [review]
I haven't used Ember in a minute, but I'm happy that folks are continuing to use this library!

**Comment by davidgoli** [comment]
@veelci published 0.0.15 to npm

**Comment by veelci** [comment]
Thanks!

**Pull request merged**
